In [218]:
import numpy as np

# Creating Arrays

In [219]:
a = np.array([1,2,3])
a.shape, a

((3,), array([1, 2, 3]))

In [220]:
b= np.array([(1.5,2,3),(4,5,6)], dtype=float)
b.shape, b

((2, 3), array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]))

In [221]:
c = np.array([[(1.5,2,3),(4,5,6)], [(7.5,8,9),(10,11,12)]], dtype=float)
c.shape, c

((2, 2, 3), array([[[ 1.5,  2. ,  3. ],
         [ 4. ,  5. ,  6. ]],
 
        [[ 7.5,  8. ,  9. ],
         [10. , 11. , 12. ]]]))

# Initial Placeholders

In [222]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [223]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [224]:
np.arange(10,25,5) # evenly spaced values (step value)

array([10, 15, 20])

In [225]:
np.linspace(0,2,9) # evenly spaced values (no of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [226]:
np.full((2,2), 7) # constant array

array([[7, 7],
       [7, 7]])

In [227]:
np.eye(2) # identity matrix

array([[1., 0.],
       [0., 1.]])

In [228]:
np.random.random((2,2))

array([[0.35366991, 0.61246624],
       [0.23830486, 0.48063953]])

Empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [229]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# I/O
#### Saving & Loading on Disk

In [230]:
s_a = np.array([1,2,3])
s_b = np.array([4,5,6])
!mkdir -p tmp
np.save('tmp/s_a_array', s_a)
np.load('tmp/s_a_array.npy')

array([1, 2, 3])

In [231]:
np.savez('tmp/s_a__s_b_array.npz', s_a, s_b)
npz = np.load('tmp/s_a__s_b_array.npz')
npz.files, npz['arr_0'],npz['arr_1'], npz.f.arr_0, npz.f.arr_1

(['arr_0', 'arr_1'],
 array([1, 2, 3]),
 array([4, 5, 6]),
 array([1, 2, 3]),
 array([4, 5, 6]))

#### Saving & Loading Text Files

In [232]:
t_a = np.random.random((2,2))
np.savetxt("tmp/myfile.txt", t_a, delimiter=" ")
np.genfromtxt("tmp/myfile.txt", delimiter=" ")
np.loadtxt("tmp/myfile.txt") # delimiter should be space

array([[0.58572764, 0.95163349],
       [0.78673811, 0.64822074]])

In [233]:
i_a = np.random.random((3,2))
i_a.shape, \
len(i_a), \
i_a.ndim, \
i_a.size, \
i_a.dtype, \
i_a.dtype.name, \
i_a.astype(int)


((3, 2), 3, 2, 6, dtype('float64'), 'float64', array([[0, 0],
        [0, 0],
        [0, 0]]))

In [234]:
np.info(np.ndarray)

 ndarray()

ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer interface, optional
    Used to fill the array with data.
of

### Arithmetic Operations

In [235]:
a = np.linspace(5,9,5)
b = np.ones(5)
a, a-b, a+b, a/(a+b), a*(a+b), np.multiply(a, b), np.exp(a), \
np.sqrt(a), np.sin(a), np.log(a), a.dot(b)


(array([5., 6., 7., 8., 9.]),
 array([4., 5., 6., 7., 8.]),
 array([ 6.,  7.,  8.,  9., 10.]),
 array([0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ]),
 array([30., 42., 56., 72., 90.]),
 array([5., 6., 7., 8., 9.]),
 array([ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704,
        8103.08392758]),
 array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]),
 array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]),
 array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458]),
 35.0)

### Comparison

In [236]:
# Element-wise
print(a == b, a<b, a>b)
# Array-wise
np.array_equal(a,b) 

[False False False False False] [False False False False False] [ True  True  True  True  True]


False

### Aggregate Functions

In [237]:
a.sum(), a.min(), a.max(), a.mean()

(35.0, 5.0, 9.0, 7.0)

In [238]:
a_2d = np.array([(2,4),(3,6)])
a_2d.max(), a_2d.max(axis=0), a_2d.max(axis=1), a_2d.cumsum(axis=1)

(6, array([3, 6]), array([4, 6]), array([[2, 6],
        [3, 9]]))

### Copying & Sorting

In [239]:
a.view()
np.copy(a)
a.copy() # deep copy
a.sort(axis=0)

### Subsetting, Slicing, Indexing

In [240]:
ssi_a = np.array([1,2,3])
ssi_b = np.array([(1,2,3),(4,5,6)])
ssi_a[2], ssi_b[1,2], ssi_a[0:2], ssi_b[0:2, 1], ssi_b[:1], \
ssi_b[1, ...]

(3, 6, array([1, 2]), array([2, 5]), array([[1, 2, 3]]), array([4, 5, 6]))

In [241]:
ssi_b, ssi_b[: :-1] # reversed array

(array([[1, 2, 3],
        [4, 5, 6]]), array([[4, 5, 6],
        [1, 2, 3]]))

In [242]:
ssi_b[ssi_b>2] # select elements less than 2

array([3, 4, 5, 6])

### Fancy Indexing
[Exploring Fancy Indexing](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html)

In [272]:
f_a = np.arange(12).reshape(3,4)
print(f_a, '\n')
row = np.array([0,1,2])
col = np.array([2,1,0])
print(f_a[row,col], '\n')
# f_a[row[:, np.newaxis], col]
row[:].shape, row[:, np.newaxis].shape
print(row[:, np.newaxis], '\n')
f_a[row[:, np.newaxis], 1], f_a[row[:, np.newaxis], col] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[2 5 8] 

[[0]
 [1]
 [2]] 



(array([[1],
        [5],
        [9]]), array([[ 2,  1,  0],
        [ 6,  5,  4],
        [10,  9,  8]]))